=== JPhilipp/QuestML/script/quest.dtd
<!ENTITY % setStateContent "(string | state | number)*">

<!ENTITY % textContent "#PCDATA | image | break| emphasis | strong | display | poem | span | link">

<!ENTITY % stationContent "(image | music | text | image | table| embed | (%setStateContent;))*,
                            ( (choice*, input*)*  | choose )
                            ">

<!ENTITY % chooseContent "(%setStateContent;), choose">

<!ELEMENT quest (about, style?, station+)>
<!ATTLIST quest debug (false | true) 'false'
                language (english | german) 'english'
                >

<!ELEMENT about (
                  ( (title, author)* ),
                  ( (cover?, intro?, date?, email?, homepage?)* )
                ) >

    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>

    <!ELEMENT cover EMPTY>
    <!ATTLIST cover source CDATA #REQUIRED>
    <!ELEMENT intro (#PCDATA)>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT homepage (#PCDATA)>

<!ELEMENT station (
                    (comment?, include*, if*, else) |
                    (comment?, include*, (%setStateContent;), if*, else) |
                    (comment?, include*, (%setStateContent;), %stationContent;) |
                    (include*, comment?, if*, else) |
                    (include*, comment?, (%setStateContent;), if*, else) |
                    (include*, comment?, %stationContent;)
                  )
                  >
    <!ATTLIST station id CDATA #REQUIRED
              states (persist | reset) 'persist'>

    <!ELEMENT include (in+)>
    <!ATTLIST include check CDATA #IMPLIED
                      process (before | after | exclusive) 'after'>
    <!ELEMENT in EMPTY>
    <!ATTLIST in check CDATA #IMPLIED>
    <!ATTLIST in station CDATA #REQUIRED>

    <!ELEMENT comment (#PCDATA)>
    <!ELEMENT image EMPTY>
    <!ATTLIST image source CDATA #REQUIRED
                    check CDATA #IMPLIED
                    text CDATA #IMPLIED
                    class CDATA #IMPLIED
                    default (true | false) 'false'>
    <!ELEMENT music EMPTY>
    <!ATTLIST music source CDATA #REQUIRED
                    check CDATA #IMPLIED
                    loop (true | false) 'false'
                    default (true | false) 'false'>

    <!ELEMENT table (caption?, tr*)>
    <!ATTLIST table class CDATA #IMPLIED>
    <!ELEMENT caption (#PCDATA)>
    <!ELEMENT tr (th | td)+>
    <!ATTLIST tr class CDATA #IMPLIED>
    <!ELEMENT th (#PCDATA)>
    <!ATTLIST th rowspan CDATA #IMPLIED
                 colspan CDATA #IMPLIED
                 class CDATA #IMPLIED>
    <!ELEMENT td (#PCDATA)>
    <!ATTLIST td rowspan CDATA #IMPLIED
                 colspan CDATA #IMPLIED
                 class CDATA #IMPLIED>

    <!ELEMENT text (%textContent; | choice)*>
    <!ATTLIST text check CDATA #IMPLIED
                   class CDATA #IMPLIED>
        <!ELEMENT break EMPTY>
        <!ATTLIST break type (normal | strong) 'normal'>
        <!ELEMENT emphasis (#PCDATA)>
        <!ELEMENT strong (#PCDATA)>
        <!ELEMENT display (#PCDATA)>
        <!ELEMENT poem (#PCDATA)>
        <!ELEMENT link (#PCDATA)>
        <!ATTLIST link to CDATA #REQUIRED
                       target (blank | self | top) 'blank'>

    <!ELEMENT state EMPTY>
    <!ATTLIST state name CDATA #REQUIRED
                  value (false | true) 'true'>
    <!ELEMENT number EMPTY>
    <!ATTLIST number name CDATA #REQUIRED
                     value CDATA #REQUIRED
                     min CDATA #IMPLIED
                     max CDATA #IMPLIED>
    <!ELEMENT string EMPTY>
    <!ATTLIST string name CDATA #REQUIRED
                     value CDATA #REQUIRED>
    <!ELEMENT choice (%textContent; | string | state | number)*>
    <!ATTLIST choice station CDATA #REQUIRED
                     check CDATA #IMPLIED
                     area CDATA #IMPLIED
                     class CDATA #IMPLIED>
    <!ELEMENT input (%textContent;)*>
    <!ATTLIST input station CDATA #REQUIRED
                     check CDATA #IMPLIED
                     name CDATA #IMPLIED
                     class CDATA #IMPLIED>

    <!ELEMENT embed EMPTY>
    <!ATTLIST embed source CDATA #REQUIRED
                    check CDATA #IMPLIED
                    class CDATA #IMPLIED
                    merge (true | false) 'false'>

<!ELEMENT if ( (%chooseContent;) | (%stationContent;) )>
<!ATTLIST if check CDATA #IMPLIED>
<!ELEMENT else ( (%chooseContent;) | (%stationContent;) )>
    <!ELEMENT choose EMPTY>
    <!ATTLIST choose station CDATA #REQUIRED>

<!ELEMENT style (
                  (background?, font?, content?, class*)*
                )
    >
    <!ELEMENT background EMPTY>
        <!ATTLIST background color CDATA 'default'
                             image CDATA 'default'
                             repeat (no-repeat | repeat-x | repeat-y| repeat) 'no-repeat'>
    <!ELEMENT font EMPTY>
        <!ATTLIST font color CDATA 'default'
                       family CDATA 'default'
                       weight CDATA 'default'
                       size CDATA 'default'
                       links (normal | underlined) 'underlined'>
    <!ELEMENT content EMPTY>
        <!ATTLIST content width CDATA '500px'
                         left CDATA 'default'
                         top CDATA 'default'>
    <!ELEMENT class EMPTY>
        <!ATTLIST class name CDATA #REQUIRED
                        inherits CDATA #IMPLIED
                        style CDATA #REQUIRED>

=== JPhilipp/QuestML/quest/test.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE quest SYSTEM "../script/quest.dtd">
<quest debug="true">

<about>
    <title>Test</title>
    <author>Philipp Lenssen</author>
</about>

<station id="start">
    <state name="has sword"/>
    <state name="has diamond"/>
    <state name="has magic staff"/>
    <string name="player has" value="{states 'has'}"/>

    <text>Your bag contains contains [player has].<break /></text>
    <text check="[has sword]">Yes, you have a sword.<break /></text>
    <text check="[has sceptre]">Yes, you have a sceptre.<break /></text>
    <text check="not [has sceptre]">No, you don't have a sceptre.<break /></text>

    <choice station="main">Go to main</choice>
</station>

<station id="main">
    <text>bla bla bla</text>
    <choice station="start">Start over</choice>
</station>

</quest>

=== JPhilipp/QuestML/quest/ql.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE quest SYSTEM "../script/quest.dtd">
<quest>

<about>
    <title>Battle sample</title>
    <author>Philipp Lenssen</author>
</about>

<station id="start">
    <text>
        There's a big monster in front of you
        blocking the path.
        <emphasis>This could be dangerous!</emphasis>
    </text>
    <image source="media/monkey.gif"/>
    <number name="player skill" value="10"/>
    <number name="player stamina" value="10"/>
    <number name="enemy skill" value="10"/>
    <number name="enemy stamina" value="10"/>
    <string name="after win" value="new path"/>
    <choice station="battle">
        Let's start the battle
        Hip hip hooray
        <state name="player started battle2" value="true"/>
    </choice>
</station>

<station id="battle">
    <comment>This battle functionality can be reused</comment>
    <number name="player power" value="[player skill] + {random 2, 12}"/>
    <number name="enemy power" value="[enemy skill] + {random 2, 12}"/>
    <if check="[player power] = [enemy power]">
        <text>
            Both of your swords miss the other.
            Stamina stays the same.
        </text>
        <choice station="battle">
            Battle again
        </choice>
    </if>
    <if check="[player power] greater [enemy power]">
        <text>
            You hit the enemy and wound him.
        </text>
        <number name="enemy stamina" value="[enemy stamina] - 2"/>
        <choice station="battle result">
            Continue
        </choice>
    </if>
    <else>
        <text>
            The enemy hits you and it hurts.
        </text>
        <number name="player stamina" value="[player stamina] - 2"/>
        <choice station="battle result">
            Continue
        </choice>
    </else>
</station>

<station id="battle result">
    <if check="[player stamina] lower 1">
        <text>
            The enemy wounds you deadly.
            <strong>Game over.</strong>
        </text>
    </if>
    <if check="[enemy stamina] lower 1">
        <text>
            You kill the enemy.
            You can continue your game.
        </text>
        <choice station="[after win]">
            You continue
        </choice>
    </if>
    <else>
        <text>
            Both of you are still standing.
            Your Stamina is [player stamina], the
            enemy stamina is [enemy stamina].
        </text>
        <choice station="battle">
            Battle again
        </choice>
    </else>
</station>

<station id="new path">
    <text>
        You're on a new path, leaving the monster behind
        you... <break/>
        <emphasis>This is just the beginning of the quest,
        but this sample is over.</emphasis>
    </text>
</station>

</quest>

=== JPhilipp/QuestML/quest/unicorn.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE quest SYSTEM "../script/quest.dtd">
<quest debug="true">

<about>
    <title>Your title</title>
    <author>Your name</author>
</about>


<station id="unicorn continue">
<text>The End</text>
</station>


<station id="start">
<text>"What's my name?" she asks.
</text><input station="the answer" name="the animal">You answer.</input>
</station>


<station id="the answer">
<if check="[the animal] = 'unicorn'">
<text>"Oh, you do know me! Indeed, I'm a [the animal]." she cries.
</text>
<state name="knows unicorn"/>
<choice station="unicorn continue">Continue</choice>
</if>
<else>
<text>"So that's what you take me for, ... [the animal]?" she sighs.
</text>
<choice station="unicorn continue">Continue</choice>
</else>
</station>



</quest>

=== JPhilipp/QuestML/quest/little_bird.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE quest SYSTEM "../script/quest.dtd">
<quest debug="false">

<about>
    <title>Little Bird</title>
    <author>Philipp Lenssen</author>
<date>26.04.01</date><cover source="media/bird.gif"/><intro>This is just a sample quest using the include command. By the station interconnections you can see the bird is seperated. The bird acts differently depending on what happens (the player can find an apple to feed it to the bird). Station interconnections can be displayed by pressing Ctrl+F1 in the editor.</intro>
    <homepage>http://www.outer-court.com</homepage>
    <email>lenssen@hitnet.rwth-aachen.de</email></about>


<style><background color="rgb(0,0,0)" repeat="no-repeat"/><font color="rgb(255,255,255)" family="&quot;times new roman&quot;, serif" links="normal"/><content width="450px"/>
<class name="loudVoice" inherits="" style="font-size: 120%"/>
</style>


<station id="start">
<text>You're standing in front of a door. The door seems to be open.</text>
<choice station="room entrance">Enter the door.</choice>
<choice station="door wait some time">Wait some time.</choice>
</station>


<station id="room put back book">
<text>You put back the book. 
</text>
<choice station="room bookcase">Continue</choice>
</station>


<station id="room entrance">
<text>You're inside a large room.<break/>You can see a bookcase, a wooden drawer, and a carpet with strange patterns. This room smells of dust.
</text>
<choice station="room bookcase">Examine the bookcase.</choice>
<choice station="room drawer">Search the drawer.</choice>
<choice station="room carpet">Examine the carpet.</choice>
<choice station="start">Leave the room.</choice>
</station>


<station id="room drawer">
<text>The drawer is closed. A key might help here. 
</text>
<choice station="room entrance">Continue.</choice>
</station>


<station id="room carpet sit">
<text>You sit down a bit. You suddenly feel a little dizzy. 
</text>
<choice station="back">You get up again.</choice>
</station>


<station id="room carpet">
<text check="[visits(room carpet)] = 0">You try to make sense of the pattern by walking around the carpet and examining it from all sides. It seems slightly familiar. You touch the thick fabric, and pull it to the side.
</text>
<text check="[visits(room carpet)] greater = 0">You are standing close to a carpet.
</text>
<text>
A door shows up below the carpet. It seems to be open.
</text>
<choice station="passage entrance">Enter the passage downways.</choice>
<choice station="room carpet sit">Sit down on the carpet.</choice>
<choice station="room entrance">Go to the entrance of the room.</choice>
</station>


<station id="room bookcase other books">
<text>You go through some of the other books, but don't notice anything special. 
</text>
<choice station="back">Continue</choice>
</station>


<station id="room bookcase keep book">
<text>You put the book in your pocket.
</text>
<state name="has glowing black book"/>
<choice station="room bookcase">Continue.</choice>
</station>


<station id="room bookcase black book">
<text>As you open the pages to the black book, a strange glow lights the room. You can hear a voice coming from all sides.<break/>
</text>
<text class="loudVoice">"Put down the book, stranger!"
</text>
<choice station="room put back book">You put back the black book.</choice>
<choice station="room bookcase keep book">You keep the book.</choice>
</station>


<station id="room bookcase">
<text>You're standing in front of a bookcase. Some of these books seem to fall apart.
</text>
<text check="not [has glowing black book]">A large black leathered book catches your attention. You can't decipher its title, as it seems to be written in magic language. 
</text>
<choice station="room bookcase black book" check="not [has glowing black book]">Pick up the black book.</choice>
<choice station="room bookcase other books">Examine some books.</choice>
<choice station="room entrance">Go back to the entrance of the room.</choice>
</station>


<station id="passage entrance">
<text check="[has glowing black book]">You're at the entrance of a passage. The glowing black book shows you the way down the passage.
</text>
<text check="not [has glowing black book]">Everything is dark around here. You can't see your own hand. Maybe you need a light. 
</text>
<choice station="passage deeper" check="[has glowing black book]">You go deeper down the passage.</choice>
<choice station="room carpet">You go up again.</choice>
</station>


<station id="passage deeper">
<text>You're deep inside the underground passage. Spiders crawl beneath your shoes, and there's a cold wind biting your face. After a bit of walking, the passage and at a closed, metal door. You can hear a high pitched voice screaming from inside. The door is closes.
</text>
<choice station="back">You go back and up the passage again.</choice>
</station>


<station id="door wait some time">

<if check="{random 0, 100} greater 35">
<text>You wait around a bit, and get hungry. You pick up a shiny red apple from a tree close to you.
</text>
<state name="has red apple"/>
<choice station="door eat apple">Eat the apple.</choice>
<choice station="start">Don't eat the apple.</choice>
</if>
<else>
<text>You wait around a bit, but nothing special happens. 
</text>
<choice station="start">Continue</choice>
</else>
</station>


<station id="door eat apple">
<text>The apple tastes good. Your appetite is satisfied for now.</text>
<state name="not has red apple"/>
<choice station="start">Continue.</choice>
</station>


<station id="bird sings">
<text>
The bird sings a song:
<poem>
There once was a love bird
High up in the sky
All day flying around
Doesn't matter much why
Well it mighta been lonely
Or a little bit sad
Or it might well just be
Love birds are plain mad
</poem>
</text>
<choice station="[station of bird]">Continue.</choice>
</station>


<station id="bird in room"><include>
<in station="room*"/>
</include>
<number name="birdReaction" value="{random 1, 8}"/>
<text><break type="strong"/></text>
<text check="[birdReaction] = 1">A little bird is flying around you, chirping.</text>
<text check="[birdReaction] = 2">A little bird is flying around you wildly. It seems to be a bit hungry.</text>
<text check="[birdReaction] = 3">A litte bird is sitting down on your shoulder.</text>
<text check="[birdReaction] greater = 4 and [fed red apple to bird]">The little bird seems to like you and sings a song in bird voice. It's a song about love.
</text>
<string name="stationOfBird" value="[qmlStation]"/>
<choice station="bird feed apple" check="[has red apple] and not [birdReaction] = 4">Feed the apple to the bird.</choice>
<choice station="bird sings" check="[birdReaction] greater = 4 and [fed red apple to bird]">Listen a bit to the little bird.
</choice>
</station>


<station id="bird feed apple">
<text>The bird likes the red apple and eats it.</text>
<state name="not has red apple"/>
<state name="fed red apple to bird"/>
<choice station="[stationOfBird]">Continue.</choice>
</station>



</quest>

=== JPhilipp/QuestML/quest/candle.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE quest SYSTEM "../script/quest.dtd">
<quest debug="true">

<about>
    <title>Candle</title>
    <author>Philipp Lenssen</author>
</about>


<station id="southern room">
<text>You're in the southern room. There's just one exit. A little rat is crawling on the ground.</text>
<text check="[gave cheese]">The rat seems all happy and fat.</text>
<choice station="southern room" check="[took cheese] and not [gave cheese]">Feed the rat with your cheese
<state name="gave cheese"/>
</choice>
<choice station="start">Leave the room through the exit</choice>
</station>


<station id="northern room">

<if check="not [took cheese]">
<text>You're in the northern room.
There's some cheese on the ground.</text>
<choice station="[qmlStation]">Take the cheese
<state name="took cheese"/>
</choice>
<choice station="start">Leave the room</choice>
</if>
<else>
<text>You're in the northern room.</text>
<choice station="start">Leave the room</choice>
</else>
</station>


<station id="find a candle">
<text>You look around. <strong>Yes!</strong> There you found a candle.</text>
<state name="has candle"/>
<choice station="back">You light the candle</choice>
</station>


<station id="end">
<text>You despair. This adventure is over.</text>
</station>


<station id="start">

<if check="not [has candle]">
<text>You're inside a dark room.
</text>
<choice station="find a candle">Find a candle</choice>
<choice station="end">Despair</choice>
</if>
<else>
<text>The room you're in is brightly lit by your candle.
There's a door leading to the north, and one leading to the south.
</text>
<choice station="northern room">Go north</choice>
<choice station="southern room">Go south</choice>
</else>
</station>


<station id="smell">
<include check="not [checked bat]">
    <in station="start"/>
    <in station="*room"/>
</include>
<text><break type="strong" />
There's a funny smell surrounding you.</text>
<choice station="smell find out" check="[has candle]">Find out about the funny smell</choice>
</station>

<station id="smell find out">
<text>There's a rotting vampire bat flying around at the top of the ceiling!
</text>
<string name="stationBack" value="[qmlLastStation]"/>
<choice station="bat catch">Catch the bat</choice>
<choice station="[stationBack]">Leave the bat be</choice>
</station>

<station id="bat catch">
<text>The bat is too quick for you to catch.</text>
<state name="checked bat"/>
<choice station="[stationBack]">Leave the bat be</choice>
</station>

</quest>
